---
spring:
  profiles: dev1
  application:
    name: eurake1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否注册自身到eureka服务器
    # register-with-eureka: false
    # 是否从eureka上获取注册信息
    # fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/

---

spring:
  profiles: dev2
  application:
    name: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否注册自身到eureka服务器
#    register-with-eureka: false
    # 是否从eureka上获取注册信息
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/