spring:
  application:
    name: auth-server
  datasource:
    username:
    url:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /uaa
  port: 5000
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    serviceUrl:
      defaultZone1: http://localhost:8761/eureka/
      defaultZone2: http://localhost:8762/eureka/