spring:
  application:
    name: config-server
  profiles:
    active: native
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone1: http://localhost:8761/eureka/
      defaultZone2: http://localhost:8762/eureka/