server:
  port: 5555
spring:
  profiles:
    include: zuul
    active: dev
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone1: http://localhost:8761/eureka/
      defaultZone2: http://localhost:8762/eureka/

zuul:
  retryable: true
