server:
  port: 5555
spring:
  profiles:
    include: zuul
    active: dev
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone1: http://localhost:8761/eureka/
      defaultZone2: http://localhost:8762/eureka/

zuul:
  retryable: true

security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:7777/uaa/oauth/token
      user-authorization-uri: http://localhost:7777/uaa/oauth/authorize
      client-id: zuul_server
      client-secret: secret
    resource:
      jwt:
        key-value: springcloud123